apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-goinfra
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - cluster: in-cluster
          url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'goinfra-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/maruina/appset-poc.git
        targetRevision: HEAD
        path: goinfra
        helm:
          releaseName: "goinfra"
          valueFiles:
            - "values.yaml"
            - "values-{{cluster}}.yaml"
          parameters:
            - name: go-infrabin.podAnnotations.gitsha #mshell-service.deployment.image.tag
              value: ${ARGOCD_APP_REVISION}
      destination:
        server: '{{url}}'
        namespace: infrabin
